import type { Metadata } from "next";
import "./globals.css";
import StatusSelector from "@/components/StatusSelector";
import GenderSelector from "@/components/GenderSelector";
import { Suspense } from "react";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div className="space-y-2 mt-5">
          <Suspense fallback={<div>Loading...</div>}>
            <StatusSelector />
            <GenderSelector />
          </Suspense>
        </div>
        {children}
      </body>
    </html>
  );
}
